image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  LOCKSIDIAN_IMAGE: registry.gitlab.com/locksidian/locksidian-ci:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $LOCKSIDIAN_IMAGE .
    - docker push $LOCKSIDIAN_IMAGE
